### ISSUE TITLE
Add R Kernel and RStudio

### ISSUE THREAD

**Issue by silasprincipe** [iobis/obis-hub#1]
We need to add the R kernel and RStudio option in our JupyterHub implementation.

Like this: 
![](https://hpc.vub.be/_images/jupyterhub-rstudio-launcher.png)

Our target is to have an environment like this one: https://mybinder.org/v2/gh/rocker-org/binder/master?urlpath=rstudio

**Comment by pieterprovoost** [comment]
R kernel is installed but Rstudio is not straightforward, we'll need a more sophisticated JupyterHub setup with https://github.com/jupyterhub/jupyter-rsession-proxy.

> Multiuser Considerations
This extension launches an rstudio server process from the jupyter notebook server. This is fine in JupyterHub deployments where user servers are containerized since other users cannot connect to the rstudio server port. In non-containerized JupyterHub deployments, for example on multiuser systems running LocalSpawner or BatchSpawner, this not secure. Any user may connect to rstudio server and run arbitrary code.

**Comment by silasprincipe** [comment]
Great @pieterprovoost, I think the most important for this first moment is to have the R kernel. I will close this issue and we can come back to the RStudio implementation later.
